org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.parallel=true
org.gradle.caching=true
#org.gradle.java.home=/snap/android-studio/current/jbr
#org.gradle.java.installations.paths=/snap/android-studio/current/jbr